### ISSUE TITLE
EnableAccessRequest via CloudFoundary Operations Java Client silently ignores the call when Plan Name is incorrect

### ISSUE THREAD

**Issue by gsingh2712** [cloudfoundry/cf-java-client#1045]
If Plan Name is wrong none of the Error/Exception is caught, I expected at least any one the Error trapping blobs to work either **OnErrorResume()** or **catch(Exception exp)**. 
Check Snippet in the Last

While CF CLI when using enableAccess command gives proper Error message
```
cf enable-service-access <service> -p <plan_name>
"The Plan <plan_name> could  not be found for service <service>"
```
As per Doc behaviour cloudfoundry-operations should behave same as CLI

> cloudfoundry-operations – An API and implementation that corresponds to the Cloud Foundry CLI operations. This project builds on the cloudfoundry-client and therefore has a single implementation.

```
EnableServiceAccessRequest enableServiceAccessRequest EnableServiceAccessRequest.builder().serviceName(serviceName).servicePlanName(plan).build();
 try {
      CloudFoundryOperations.serviceAdmin().enableServiceAccess(enableServiceAccessRequest)
      .onErrorResume(e -> {
          LOGGER.error("Enable Service Access plan failed {}", e.getMessage());
        return Mono.empty();
       }).block();
} catch (Exception e) {
      LOGGER.error("Enable Service Access plan failed {}", e.getMessage());
}
```

If feel in these functions are silently ignoring if plan Name is Wrong

https://github.com/cloudfoundry/cf-java-client/blob/4ce8018050f69619cc9e1eb61a8a7f5a36e2d5c7/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/serviceadmin/DefaultServiceAdmin.java#L124

https://github.com/cloudfoundry/cf-java-client/blob/4ce8018050f69619cc9e1eb61a8a7f5a36e2d5c7/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/serviceadmin/DefaultServiceAdmin.java#L252

**Comment by twoseat** [comment]
To correct your understanding slightly, the quote you provide deliberately uses the word 'corresponds' rather than 'replicates', because it provides broadly equivalent functionality without trying be an exact replication of the CLI. One example is that we don't have the `--guid` flag of the CLI because we provide the guid in every response 'for free'.

More significantly, we continue execution for a range of errors. That is partly because any value entered (in your example, the plan name) is assumed to have come from an external system, and to have been validated by that system. It is also because we can't assume that at the other end of the error message is an intelligence that can respond to it.

In your scenario, if you feel there is a risk of the plan name being entered wrong I suggest you start with a lookup of the plan to validate that it exists.

I'll leave this issue open for a while in case you have a response.

**Comment by dmikusa-pivotal** [comment]
Closing as this has been open w/out comment for a while. Thanks
