### ISSUE TITLE
Missing CloudFoundryOperations.services().upgrade() method

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/cf-java-client#1052]
### Expected behavior

As a cf-java-client user
* in order to trigger the equivalent of `cf update-service --upgrade` CF CLI calls using CloudFoundryOperations
* I need to be able to provide a [maintenance_info](https://apidocs.cloudfoundry.org/13.2.0/service_instances/update_a_service_instance.html) in a new  ` org.cloudfoundry.operations.services._UpgradeServiceInstanceRequest` request accepted from a new `CloudFoundryOperations.services().upgrade()`method

### Current behavior

CloudFoundryOperations.services().update() does not accept a maintenance_info

### Workaround

Use low-level cf-java-client api contributed by @twoseat in  9fb5485 as a resolution for #1048

**Comment by twoseat** [comment]
Can you explain the need for the `maintenance-info` in this scenario? I'm fine with having a separate `upgrade` command where the CLI (mis)uses the `update` command, but based on the CLI command we only need to provide something to identify the service instance.

**Comment by gberche-orange** [comment]
@twoseat the [PUT /v2/service_instances/:guid](https://apidocs.cloudfoundry.org/13.3.0/service_instances/update_a_service_instance.html) CC API accepts a `maintenance_info`, but you're right, an `UpgradeServiceInstanceRequest` could only take argument to identify the service instance, and infer the `maintenance_info` to pass by looking it up in the associated service plan.

A simpler alternative might just be to accept a `MaintenanceInfo` into the existing `org.cloudfoundry.operations.services._UpdateServiceInstanceRequest` and keep the `update()` method.

**Comment by twoseat** [comment]
I'm slightly hampered here as I don't have an upgradeable plan to play with! My initial assumption was that in the background a command was sent to the CC API that said "upgrade this to the latest version" (which is what the CLI command in effect does). But it appears from what you're saying, plus the doc, that while the CLI assumes the latest version, the actual request is to upgrade to a specific version. I guess normally that would be the latest, but there might be some compatibility reason not to.

So can you confirm that what you'd actually like is a way to specify an arbitrary version to upgrade to? If so I think that actually fits better with the existing `update()` logic rather than introducing a new `upgrade()` (though I'll have to think about that a little more).

**Comment by gberche-orange** [comment]
> So can you confirm that what you'd actually like is a way to specify an arbitrary version to upgrade to? If so I think that actually fits better with the existing update() logic rather than introducing a new upgrade() (though I'll have to think about that a little more).

Yes, the existing update method accepting an additional  `MaintenanceInfo` parameter  would serve the upgrade the use-case

**Comment by gberche-orange** [comment]
thanks @twoseat !

(I'm currently away for a sick leave but plan to test and use your fix when I return hopefully in 2 weeks).

**Comment by twoseat** [comment]
Be well!

**Comment by gberche-orange** [comment]
I've bumped my dependency and tested, works perfect, thanks @twoseat !
