### ISSUE TITLE
Issue with refresh token

### ISSUE THREAD

**Issue by sms0070** [cloudfoundry/cf-java-client#1058]
Hi,

I see a line in the code for parsing tokens in AbstractUaaTokenProvider.
String jws = token.substring(0, token.lastIndexOf('.') + 1);

Why are we creating a substring till "." ? 
what does "." imply here?

We have a refresh token like "2cde612516dc471589fd96c01a0bcbed-r", and this line returns an empty string for this token.

Regards,
Suyash

**Comment by twoseat** [comment]
https://jwt.io/introduction/ has an explanation of the `.` (under "What is the JSON Web Token structure?"). So the refresh token you have quoted is actually just the signature part of a full JSON Web Token. I wouldn't have expected you to be given just the signature part from UAA - is that what you're seeing?

**Comment by sms0070** [comment]
yes, I only get that from UAA.

**Comment by sms0070** [comment]
If we follow [this](https://docs.cloudfoundry.org/api/uaa/version/74.23.0/index.html#refresh-token),
you'll notice that, refresh-token does not contain the expiry information and is only the signature part.

hence, can we handle this in the library directly? otherwise, I'll have to make specific changes.

Also, if there a way to refresh the "refresh_token" if it's expired?

**Comment by twoseat** [comment]
As part of our integration tests we log the access and refresh tokens we've been issued (in case we need it for debugging). Here's the refresh token from a run I just did, with {foo} marking a long string:

`eyJhciiJ{foo}iJVQfQ.eyJqk{foo}ZjMiQ.XgEG-nN{foo}6BdXFm9Q`

This gives me some confidence that what you're getting isn't what we would consider a refresh token. In theory we should be handling all of this for you, so that makes me wonder if you're bypassing some of what we do to handle things manually. Is that possible?

Refresh tokens are refreshed automatically since this: https://github.com/cloudfoundry/cf-java-client/commit/af56fdbec8e5d8c0e7216ebd5d94e240f99c8e35

**Comment by torsten-sap** [comment]
Hi @twoseat,
I will try to add some details to clarify the issue. The CF UAA has the possibility to return the refresh token in two different formats: "jwt" and "opaque". See the [documentation](https://docs.cloudfoundry.org/api/uaa/version/74.23.0/index.html#refresh-token).

You are talking about the token type "jwt" where you have the possibility to inspect the refresh token and get the validity out of it. @sms0070 is referring to the token type "opaque" for which you do not have this possibility. And as you do not have this validity information the refresh token (or better, its "reference") can basically stop to work at any unknown time. 

One benefit of the opaque tokens is that they can be revoked.

-Torsten

**Comment by twoseat** [comment]
Thanks @torsten-sap - that makes more sense, and gives me something I can hopefully do about the problem.

**Comment by twoseat** [comment]
I've pushed a fix for this - we only parse for logging purposes, so simple to bypass. That doesn't mean that there aren't further issues hiding behind this failure, so please check out today's snapshot (once available) and let me know if you find anything else.
