### ISSUE TITLE
Configurable TokensFile location

### ISSUE THREAD

**Issue by chrylis** [cloudfoundry/cf-java-client#208]
I'm wanting to use the plugin from a Jenkins build, which doesn't share `$HOME` between executors, and to save OAuth tokens. Instead of having to symlink `~/.cf/tokens.yml` or the like, it would be helpful for `cf.tokensFile` to be configurable instead of hardcoded.

**Comment by nebhale** [comment]
Related to #161

**Comment by nebhale** [comment]
@chrylis I'm trying to evaluate the need for this issue in the context of the work we're doing on V2.  Specifically, we've redesigned the client so that it will only need to do the OAuth dance once per instance of the client.  Since the client is thread-safe, we'd expect this to happen only a single time per VM lifetime.  I've also done some ad-hoc performance testing with the V2 client.  From Seattle on a residential Xfinity connection to PWS (`us-east-1`), I'm seeing the following:

| Action | Average Time (1000 iterations)
| --- | ---
| Initialization (endpoint lookup, no OAuth dance) | 142ms
| First Invocation (OAuth dance) | 1285ms
| Subsequent Invocations (no OAuth dance) | 125ms

So I'm thinking that we've got a handle on the performance problem you're seeing separately from whether credentials are cached.  Given that, and the fact that CI systems can pass ["secure" environment variables](http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables) (which the plugin does/will read) do you think that there's still value for sharing this value in a CI context?

**Comment by chrylis** [comment]
Not sure. This combined with the problem that pushing overwrote existing application configuration led us to just shell-script the deployment using the CLI client.

**Comment by nebhale** [comment]
We're going to fix the overwritten environment in V1, but I'm hesitant to add this to V2 at the moment.  If you're OK with it, I'm going to close this out against for now.  If you try V2 and it doesn't work for you, go ahead and open a new issue (or reopen this one) and we'll discuss further.
