### ISSUE TITLE
Run goals without POM

### ISSUE THREAD

**Issue by chrylis** [cloudfoundry/cf-java-client#209]
Several (most?) of the goals in this plugin make sense to run without a POM, such as `apps`. There doesn't seem to be any inherent need for a POM, and it would be helpful for scripting purposes to be able to invoke the goals like 

    mvn org.cloudfoundry:cf-maven-plugin:1.0.4:apps -Dcf.space=foobar

in the same way archetype goals are often invoked. I have no idea how the requirement is specified in the mojo, but when I try to run the command above in an empty directory, I get 

    [ERROR] Failed to execute goal org.cloudfoundry:cf-maven-plugin:1.0.4:apps (default-cli): Goal requires a project to execute but there is no POM in this directory

**Comment by nebhale** [comment]
@chrylis As part of the V2, we're trying to draw a brighter line as to what we think the build plugins should do.  We're leaning towards paring the functionality to only deal with application-level operations that make sense in the context of builds.  While I understand the use-case you've outlined above, I don't think adding functionality to the plugin in order to get around an environmental issue in CloudBees/Jenkins is the right way to do this.  I'd be leaning more towards getting CloudBees to support [arbitrary environment modification](http://docs.travis-ci.com/user/installing-dependencies/#Installing-Projects-from-Source) (within a container) than trying to get around the limitation using Maven.

**Comment by nebhale** [comment]
Since there's been no response on this issue in a couple of weeks, I'm going to close it.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
