### ISSUE TITLE
map-routes and unmap-routes for Blue Green deployment

### ISSUE THREAD

**Issue by sacgarg** [cloudfoundry/cf-java-client#235]
I did not see map-routes and unmap-routes for Blue Green deployment in the Maven plugin. is it planned or is there an alternate way to do the blue green deployments from this plugin?

**Comment by nebhale** [comment]
@sacgarg As the new PM for the project, I'm looking over all of the issues in the project.  @scottfrederick mentioned above we're close to delivering a functionality for blue/green deployments in the platform, removing the need for direct support in the plugin themselves.  We haven't decided precisely what will be included in the V2 build plugins, but I'll keep this in mind as a candidate.

Since this functionality will not be added to the V1 build plugins, I'm going to close out this issue.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
