### ISSUE TITLE
No way to get env variables

### ISSUE THREAD

**Issue by andreaturli** [cloudfoundry/cf-java-client#263]
I'd like to have a method to get the env variables as from the CF web console.
`app.getEnv` and `app.getEnvAsMap` don't seem to work as expected.

What am I missing?

**Comment by scottfrederick** [comment]
The current `getEnv()` and `getEnvAsMap()` methods only return user-provided environment variables (those set with `cf set-env` or the CC API equivalent). We have an open issue to expand those to support system env vars: #204.

**Comment by andreaturli** [comment]
thanks @scottfrederick, do you think it is hard to solve #204?

**Comment by andreaturli** [comment]
Alternatively @scottfrederick is there a way to discover the VCAP_SERVICES properties exposed by a service?

**Comment by scottfrederick** [comment]
The fix for this isn't hard, it just needs to be prioritized. So far it has just been a "nice to have" feature. 

Currently, the credentials for a service instance are only provided when the service instance is bound to an application, so querying the application's environment is the only way to get that information.

**Comment by andreaturli** [comment]
@scottfrederick, please consider my PR #264 as a potential fix.

**Comment by scottfrederick** [comment]
Fixed via #264
