### ISSUE TITLE
Route mapping is not working well with private domains

### ISSUE THREAD

**Issue by joek** [cloudfoundry/cf-java-client#305]
The java client is using the ("list all domains for space")[http://apidocs.cloudfoundry.org/215/spaces/list_all_domains_for_the_space_(deprecated).html] endpoint. This endpoint is not including private (owned) domains. For this reason operations based on this domains are failing.

**Comment by nebhale** [comment]
This support will be added as part of the V2 effort.  You can track its progress [here](https://www.pivotaltracker.com/story/show/101426236) and [here](https://www.pivotaltracker.com/story/show/101527360).  Since this was opened against the V1 branch, where we will not be making changes I'm going to close this out.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
