### ISSUE TITLE
upload application hung, never timeout

### ISSUE THREAD

**Issue by snzhuo** [cloudfoundry/cf-java-client#306]
hello,

we are calling function CloudFoundryClient.uploadApplication(), sometimes this call would hung there and never time out.  we actually waited more than 40 mins, then manually killed it. 

According to cloud foundry document, the default time limit for upload should be 15 mins.

**Comment by nebhale** [comment]
This support will be added as part of the V2 effort, complete with timeout.  You can track its progress [here](https://www.pivotaltracker.com/story/show/101421056).  Since this was opened against the V1 branch, where we will not be making changes I'm going to close this out.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
