### ISSUE TITLE
There is no way to create a space in an org that has no spaces

### ISSUE THREAD

**Issue by asaikali** [cloudfoundry/cf-java-client#308]
There is no constructor / method to define a client when you only name the name of the org to connect to. So if you want to connect to an org that has no spaces then create a space there is no way to do that in the client. 

The current method to create a space looks like this

```
@Override
	public void createSpace(String spaceName) {
		assertSpaceProvided("create a new space");
		UUID orgGuid = sessionSpace.getOrganization().getMeta().getGuid();
		UUID spaceGuid = getSpaceGuid(spaceName, orgGuid);
		if (spaceGuid == null) {
			doCreateSpace(spaceName, orgGuid);
		}
	}
```

notice that it depends on the sessionSpace to be present to get the Guid of the org which puts the client in a catch-22 to create a space you need to be connected to an existing space.

**Comment by nebhale** [comment]
@asaikali This support will be added as part of the V2 effort.  You can track its progress [here](https://www.pivotaltracker.com/story/show/101426218) and [here](https://www.pivotaltracker.com/story/show/106155508).  Since this was opened against the V1 branch, where we will not be making changes I'm going to close this out.  If you'd like to see it re-opened, please comment on the issue and I'll reopen it.
