### ISSUE TITLE
cf-maven-plugin: mvn cf:push fails with "503 (Service Unavailable)"

### ISSUE THREAD

**Issue by mtransier** [cloudfoundry/cf-java-client#322]
I am trying to deploy a war from maven through the cf-maven-plugin (V1.1.3). However, it fails after uploading the war:
```
[INFO] --- cf-maven-plugin:1.1.3:push (default) @ mytestapp ---
[INFO] Creating application 'mytestapp'
[INFO] Uploading 'mytestapp\target\mytestapp-server-0.0.1-SNAPSHOT.war'
[INFO] Starting application
[WARNING] GET request for "http://api.run.pivotal.io/v2/apps/<GUID>/stats" resulted in 503 (Service Unavailable); invoking error handler
```
It seems that the stats command is temporarily not available in this moment because the network trace shows that it has been successful a few times before during the same mvn run.

The same war can be deployed successfully using the cf CLI.

**Comment by nebhale** [comment]
The `503` indicates that this was a sever problem, not a client problem.  What are you expecting to happen in his case?

**Comment by mtransier** [comment]
I would expect the plugin to wait for the availability of the stats service which obviously uses 503 for telling that it is currently unavailable. Without knowing the details, I guess the app is being deployed while the maven plugin tries to request the stats too early and fails?

Note: this is happening every time. The upload works and the app is available after a short time. Nevertheless, the build fails every time.

**Comment by scottfrederick** [comment]
@mtransier You are deploying to Pivotal Web Services (`http://api.run.pivotal.io/v2/apps/<GUID>/stats`) which I believe is now defaulting to Diego instead of DEA deployment. We have discovered that CC responds to the `/stats` endpoint with a 503 in the case where the app has been deployed to a Diego cell but not started yet. This is different from the behavior of `/stats` when deployed to DEA. 

This is one of a few differences we have discovered between Diego and DEA that are likely to affect the build plugins.

**Comment by mtransier** [comment]
Ok, I see. Thanks for the answer.
Is there any workaround that I could use to be able deploying using the maven plugin for Diego?

**Comment by nebhale** [comment]
Looks like the CAPI team [has taken it on](https://www.pivotaltracker.com/n/projects/966314/stories/106702544).  I'm inclined to close this issue as it's a regression on the CAPI team.  @mtransier what's your opinion on that?

**Comment by mtransier** [comment]
Fine with me. Thanks for the link.
