### ISSUE TITLE
Question: Getting additional information about CloudServices via the client-lib; Version 1.1.3, 1.1.4

### ISSUE THREAD

**Issue by 1123** [cloudfoundry/cf-java-client#327]
In our project we need to get additional information about service instances from the cloud controller via the client-lib. Specifically, we need the organization-guid, space-guid, service-guid and service-plan-guid of each service instance.  

The Method cloudFoundryClient.getServices() returns objects of type CloudService, but these do not contain the IDs named above. Yet it takes only a couple of lines of codes in the CloudEntityResourceMapper to add these IDs. Also no additional rest calls to the cloud controller are necessary. Yet we would need to add the GUIDs to the CloudService entity. 

Would this change be a valid pull request? Or what would be the recommended way of retrieving those IDs for each service instance using the client-lib?

**Comment by nebhale** [comment]
We're currently in the midst of creating a V2 of the project.  As part of this, we will be supporting the entire Cloud Controller API with full fidelity.  Since that effort is so large, we've made the decision to not add any additional APIs to the V1 line.  So, unfortunately we're in a bit of an awkward stage where a PR isn't going to get merged into V1.

**Comment by 1123** [comment]
OK. No problem. Looking forward to V2.
