### ISSUE TITLE
No applications found on list

### ISSUE THREAD

**Issue by antechrestos** [cloudfoundry/cf-java-client#328]
Hi,

Just a question: I am currently trying to use your new client version on our cloudfoundry instance.
Doing so, I use the following code to list the applications:
```java
private void listApplicationsV3(String organizationId, String spaceId, Consumer<ListApplicationsResponse.Resource>
            applicationConsumer, Consumer<Throwable> errorConsumer, Consumer<Void> completeConsumer) {
        ListApplicationsRequestBuilder builder = ListApplicationsRequest.builder();
        if (organizationId != null)
            builder.organizationId(organizationId);
        if (spaceId != null)
            builder.spaceId(spaceId);
        ListApplicationsRequest request = builder.build();
        Publisher<ListApplicationsResponse> publisher = this.client.applicationsV3().list(request);
        Streams.wrap(publisher).consume(applicationResponse -> applicationResponse.getResources().forEach
                (applicationConsumer), errorConsumer::accept, completeConsumer::accept);
    }
```
And it lists nothing. No error is thrown either. 
Hence, I requested the __/info__ path on our cloudfoundry endpoint and got this
```javascript
{"name":"vcap","build":"2222","support":"http://support.cloudfoundry.com","version":2,"description":"Cloud Foundry sponsored by Pivotal","authorization_endpoint":"https://login.nd-cfapi.itn.ftgroup","token_endpoint":"https://uaa.nd-cfapi.itn.ftgroup","allow_debug":true}
```
My guess: we currently use a cloudfoundry v2 version and your new client only support for now v3 cloudfoundry platform. Do you confirm that?

**Comment by nebhale** [comment]
Modern versions of CF (we're trying to get to parity with 214 before updating to "latest") support both the V2 and V3 APIs in parallel with one another.  At the moment, they do not overlap in the Cloud Controller but I believe that the plan is that they eventually will (and might even in today's 223).  Because we recognize that having the future APIs in place while they're not especially useful isn't the best idea, I've prioritized the V2 Application APIs as [the next thing on the list](https://www.pivotaltracker.com/n/projects/816799).

**Comment by antechrestos** [comment]
@nebhale Thank you. Looking forward to get it then ;)

**Comment by antechrestos** [comment]
Looks good :yum:
