### ISSUE TITLE
Support authentication using an Oauth 2 token

### ISSUE THREAD

**Issue by o-orand** [cloudfoundry/cf-java-client#341]
In current v2 implementation, it is not possible to create a CloudFoundryClient using a Oauth2 token. (it is in v1). What will be the best approach to add it in v2 ? Re-introduce a CloudCredentials class ?
This could be a first step for #332.

Thanks.

**Comment by nebhale** [comment]
@o-orand This is actually better tracked by https://www.pivotaltracker.com/story/show/106214548.  At the moment this is going to be delayed until after we get the 2.0.0.M1.  The reason is that we're going to be using a different network stack for the final delivery of 2.0.0 and I don't know what's going to be required at the moment.  It's the first thing on the list post that release (although it probably won't be the first thing completed) so it'll get attention quickly.

**Comment by o-orand** [comment]
Thanks for the feedback ! It's true that it is better tracked by pivotal tracker, so I'm closing it.
