### ISSUE TITLE
Staging request management from the CF Java Client

### ISSUE THREAD

**Issue by djvdorp** [cloudfoundry/cf-java-client#392]
I am currently having some issues with Cloud Foundry, which might be due to the way that we use the `cf-java-client` to interact with our Cloud Foundry instance. 

The issue seems to occur when we initiate another staging request while the app is still staging.
This is pretty much calling `client.uploadApplication(...)` on the same application multiple times, before the first staging request is completed we have already sent 1 (or more) staging requests towards the same app.

This currently seems to result in this line in the app's (staging) log:
`encountered error: Staging error: failed to stage application: another staging request was initiated`

And this when you request the app's status from the cf cli:
`Server error, status code: 400, error code: 170002, message: App has not finished staging`

At this point, I am unsure if this is a bug in Cloud Foundry or a buildpack we're using.
However, I would expect Cloud Foundry to handle it in either 1 of these 2 ways:
1. Cancel the current staging request, and continue with the new staging request instead.
or
2. Finish the current staging request, and wait with processing the new staging request until the current one is finished.

However, to be able to implement the first way via the `cf-java-client`, I am wondering if it is (or should/could be) possible to retrieve the current running staging request for a `CloudApplication`, so that I could cancel that one, and let the newly initiated staging request pass through instead. I was unable to find a way to do so myself and would like some input on how to prevent this condition from happening in the future.

**Comment by nebhale** [comment]
What you are describing is the intended design of the Cloud Controller in Cloud Foundry.  Given multiple staging requests, the Cloud Controller (not the client) refuses requests until the running staging request has completed.  You can reproduce the behavior using the CLI to confirm this.  There is no API to cancel a currently executing staging, but you can poll to find out when staging has completed for an application.  We won't be making any changes to the client to protect against this (since it's a server-only behavior), but you can request a change to the Cloud Controller, in [their repository](https://github.com/cloudfoundry/cloud_controller_ng/issues).
