### ISSUE TITLE
Set Env variables on push

### ISSUE THREAD

**Issue by robertgmoss** [cloudfoundry/cf-java-client#432]
Hi, we'd like to be able to push our application with some environment variables, but PushApplicationRequest doesn't seem to have an method for this - is this something that will be added soon, or is there an alternative way of doing this?

**Comment by nebhale** [comment]
@robertgmoss As a first pass, we're attempting to make the `-operations` API match the behavior of the CF CLI.  Since the CLI does not allow this at the moment, we've designed the `Applications.push()` operation in the same way.  The idiom of `push --no-start`, `set-env`, `start` from the CLI continues will work with the client as well, and that's the path I recommend you follow at the moment.

Longer term there are two paths we're looking to adopt.  The first is [reading a manifest](https://www.pivotaltracker.com/story/show/106155274) for `Applications.push()` arguments, and like the CLI, handling environment variables specified there.  I'm now thinking that we're going to delay this behavior until after the forthcoming [route-specification changes](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/N4ZDS7FVHBQFSGP724ZAXUOMISNVURIR/), but user demand could change my mind.

The second path is enhancing the API to add functionality that extends beyond the CLI.  I believe this will happen in the long term, but I'd like to reach feature parity before we start going beyond.  Again, if user-demand is high enough, the plan can change.

So at the moment, I don't plan on adding this to the API before the 2.0 release, but I will leave this issue open to attract further comment.

**Comment by nebhale** [comment]
@robertgmoss I just remembered today that there is a third path that we're going down.  We'll be supporting a programmatic `ApplicationManifest` (and the tooling to deserialize it from a YAML representation) where environment variables can be set during `push()`.

**Comment by mohanpindyala** [comment]
is programmatic ApplicationManifest supported in latest version ?

**Comment by nebhale** [comment]
@mohanpindyala It is not yet supported.

**Comment by nebhale** [comment]
Included in b334d22ef54a9b3ee8924b357c5d51e4ec03ecf5
