### ISSUE TITLE
can not set Application Envrionment

### ISSUE THREAD

**Issue by ezhang-pivotal** [cloudfoundry/cf-java-client#488]
Here is my code to set env variables
    public static void setEnvVars(
                                 String appName,
                                 Map<String, String> env) {

       for (Map.Entry<String, String> entry : env.entrySet()) {
            System.out.println("set env "+entry.getKey()+":"+entry.getValue());
            cloudFoundryOperations.applications()
                    .setEnvironmentVariable(SetEnvironmentVariableApplicationRequest.builder()
                            .name(appName)
                            .variableName(entry.getKey())
                            .variableValue(entry.getValue())
                            .build()
                    ).subscribe()
                    .doOnSuccess(v -> System.out.println(String.format("Done set env for %s", appName)))
                    .doOnError(e -> System.err.println(String.format("Error set env for %s", appName)));
        }
    }
if without subscribe, seems no request send out to cloudfoundry. With subscribe(), I can see log from the code:

```
Run task request: {taskName=demo1, cmd=java -cp testapp-1.0-SNAPSHOT.jar io.pivotal.TestApp, appLocation=http://localhost:8000/testapp-1.0-SNAPSHOT.jar}
set env taskName:demo1
set env cmd:java -cp testapp-1.0-SNAPSHOT.jar io.pivotal.TestApp
set env appLocation:http://localhost:8000/testapp-1.0-SNAPSHOT.jar
```

and log from cloudfoundry:

```
2016-06-01T15:08:32.62+0800 [API/0]      OUT Updated app with guid a6557986-c799-4cba-a652-6af6005cc99d ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2016-06-01T15:08:32.64+0800 [API/0]      OUT Updated app with guid a6557986-c799-4cba-a652-6af6005cc99d ({"environment_json"=>"PRIVATE DATA HIDDEN"})
2016-06-01T15:08:32.66+0800 [API/0]      OUT Updated app with guid a6557986-c799-4cba-a652-6af6005cc99d ({"environment_json"=>"PRIVATE DATA HIDDEN"})
```

but only 1 variables set

```
$ cf env paasapp
Getting env variables for app paasapp in org pcfdev-org / space pcfdev-space as admin...
OK

System-Provided:


{
 "VCAP_APPLICATION": {
  "application_id": "a6557986-c799-4cba-a652-6af6005cc99d",
  "application_name": "paasapp",
  "application_uris": [
   "paasapp.local.pcfdev.io"
  ],
  "application_version": "018784f4-aec5-4931-96c6-477df07a0e79",
  "limits": {
   "disk": 512,
   "fds": 16384,
   "mem": 256
  },
  "name": "paasapp",
  "space_id": "1185167c-9b43-49d7-bd9d-17ba82f0fea6",
  "space_name": "pcfdev-space",
  "uris": [
   "paasapp.local.pcfdev.io"
  ],
  "users": null,
  "version": "018784f4-aec5-4931-96c6-477df07a0e79"
 }
}

User-Provided:
appLocation: http://localhost:8000/testapp-1.0-SNAPSHOT.jar
```

**Comment by nebhale** [comment]
@ezhang-pivotal You are running the environment variable sets in parallel, which isn't thread safe.  The CF API requires you to  `PUT` the complete set of environment variables, rather than a delta each time.  From [the documentation](http://apidocs.cloudfoundry.org/237/apps/updating_an_app.html):

> Key/value pairs of all the environment variables to run in your app. Does not include any system or service variables.

This behavior is replicable with the CF CLI and even `curl` making raw requests to the REST API.  So, the proper way to do this is to single-threadedly iterate over the entries:

```
Flux
    .fromIterable(env.entrySet())
    .concatMap(entry -> cloudFoundryOperations.applications()
        .setEnvironmentVariable(SetEnvironmentVariableApplicationRequest.builder()
            .name(appName)
            .variableName(entry.getKey())
            .variableValue(entry.getValue())
            .build()))
    .subscribe(() -> System.out.println("Environment variable set"), Throwable::printStackTrace, () -> System.out.println("Complete));

**Comment by kdvolder** [comment]
@ezhang-pivotal 

What Ben suggested probably works and is fine if you don't have many variables. Otherwise it will be terribly slow. The lower-level 'client' apis are in this case much more straightforward than the higher-level 'operations' api which lets you only set one variable at a time and is subject to a race condition if you invoke the operations in parallel.

You can see how we used the lower-level api in STS here to avoid all these problems:

https://github.com/spring-projects/spring-ide/blob/16358c77b47dd4718c6ee6209c55c57b566b8de2/plugins/org.springframework.ide.eclipse.boot.dash/src-v2/org/springframework/ide/eclipse/boot/dash/cloudfoundry/client/v2/DefaultClientRequestsV2.java#L863

**Comment by ezhang-pivotal** [comment]
Thanks！
