### ISSUE TITLE
Missing spaceid in ApplicationDetail

### ISSUE THREAD

**Issue by s-bortolussi** [cloudfoundry/cf-java-client#505]
SpaceId attribute is missing from [ApplicationDetail](https://github.com/cloudfoundry/cf-java-client/blob/b51653f6733db18e00597c36f3affe52ed36643d/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/_ApplicationDetail.java).

Thus cannot get spaceId for application using

```java
public interface Applications {
...
 Mono<ApplicationDetail> get(GetApplicationRequest request);
...
}
```

However, spaceId seems to be returned and mapped from CC api call. 
```java
public final class SummaryApplicationResponse{
...
private final @Nullable String spaceId;
...
}
```

Is there a reason for not having mapped SummaryApplicationResponse.spaceId into ApplicationDetail in 

```java
public final class DefaultApplications implements Applications{
...
  private static ApplicationDetail toApplicationDetail(ApplicationStatisticsResponse applicationStatisticsResponse, SummaryApplicationResponse summaryApplicationResponse,
                                                         GetStackResponse getStackResponse, ApplicationInstancesResponse applicationInstancesResponse,
                                                         List<InstanceDetail> instanceDetails, List<String> urls) {
...
    }
...
}
```
?
 Thanks

**Comment by twoseat** [comment]
Hi @s-bortolussi - The Operations level is designed to reflect the operation of the [CF CLI](https://github.com/cloudfoundry/cli), which generally operates at the level of names rather than IDs. As a convenience we generally return the ID of the primary object, but not that of any secondary IDs.

If you need the spaceId you should drop down to the Client level where a [GetApplicationRequest](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/applications/_GetApplicationRequest.java) will give you an [AbstractApplicationEntity](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/applications/AbstractApplicationEntity.java)

**Comment by s-bortolussi** [comment]
@twoseat thanks for the quick reply
