### ISSUE TITLE
Library allows only one push operation , subsequent push of new or old app does not go through

### ISSUE THREAD

**Issue by mohanpindyala** [cloudfoundry/cf-java-client#506]
Following is the code to push app to cf. It is deploying first app fine. when I try to push second new one or for existing one, it just stays in stopped state and nothing happens . anything wrong with the code below ?
```
cfOperations
                .applications()
                .push(pushApplicationRequest)
                .doOnSuccess((v) ->
                        fromIterable(envVars)
                                .concatMap(envVar ->
                                        cfOperations
                                                .applications()
                                                .setEnvironmentVariable(envVar))
                                .subscribe(new CfSubscriber(SubcriberType.SET_ENV, app.getName())))
                .doOnSuccess((v) ->
                        fromIterable(servicesToBind)
                                .concatMap(serviceToBind ->
                                        cfOperations
                                                .services()
                                                .bind(serviceToBind))
                                .subscribe(new CfSubscriber(SubcriberType.BIND, app.getName())))
                .doOnSuccess((v) -> {
                    if (app.getStatus().equals(AppStatus.STARTED)) {

                        StartApplicationRequest startApplicationRequest = StartApplicationRequest
                                .builder()
                                .name(app.getName())
                                .build();

                        cfOperations
                                .applications()
                                .start(startApplicationRequest)
                                .subscribe(new CfSubscriber(SubcriberType.START, app.getName()));
                    }
                })
                .subscribe(new CfSubscriber(SubcriberType.PUSH, app.getName())); 
```

**Comment by mohanpindyala** [comment]
looks like a serious issue to me . If I do a push and try to do another push of existing or new app , library is just stuck it does not return.  Please look into

**Comment by twoseat** [comment]
Hi @mohanpindyala - I understand from Slack that you were looking at refactoring this code to replace `.doOnSuccess` with `.then` (or similar). Has that helped?

**Comment by mohanpindyala** [comment]
then is expecting to return Mono<void> or soemthing ,  can you give me a example where I can do something like .  Right now it doesn't work

```
 .then((v) -> {
                    if (app.getStatus().equals(AppStatus.STARTED)) {

                        StartApplicationRequest startApplicationRequest = StartApplicationRequest
                                .builder()
                                .name(app.getName())
                                .build();

                        cfOperations
                                .applications()
                                .start(startApplicationRequest)
                                .subscribe(new CfSubscriber(SubcriberType.START, app.getName()));
                    }
                })```

**Comment by mohanpindyala** [comment]
I don't understand now , everything is working  fine without any code change. Did you guys fix anything ?
I am using following versions 
```  <cloudfoundry-client-spring.version>2.0.0.BUILD-SNAPSHOT</cloudfoundry-client-spring.version>
        <cloudfoundry-operations.version>2.0.0.BUILD-SNAPSHOT</cloudfoundry-operations.version>```

**Comment by twoseat** [comment]
Hi @mohanpindyala - we didn't change anything that I would expect would make a difference to your problem. I'll close this issue for now, but if the problem comes back please let us know.

In the meantime I recommend taking a look at some of our test classes for ideas on how to structure your code. For example, this test snippet does approximately what you're looking to do. Note that it doesn't check for the started status because at the Operations level the start command takes care of that (you tell it you want the app to be in a started state, and it figures out whether it needs to do something to make that happen). You might also like to adopt the 'point free' style where the building of the request is inlined, though it's not required - after a while we found it just reads better.

https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/java/org/cloudfoundry/operations/ApplicationsTest.java#L277-L282
