### ISSUE TITLE
Knowing the application state

### ISSUE THREAD

**Issue by kiuby88** [cloudfoundry/cf-java-client#543]
Older `cf-java-client` version allowed to know the state of an application by means of `getState()` [method](https://github.com/cloudfoundry/cf-java-client/blob/v1.1.3/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/domain/CloudApplication.java#L179-L181) of `CloudApplication` class, which returned a `CloudApplication.AppState`. 

is it possible get the state of an application using the current `SNAPSHOT` client?
I found that `ApplicationSummary` provides a method, `getRequestedState()` but it looks that it provides the expected status, a couple of `Strings` `STARTED` and `STOPPED`, which are declared as [constants](https://github.com/cloudfoundry/cf-java-client/blob/40dd4823ba6d7c3076c8ac20bf5f55ef690efaaa/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/DefaultApplications.java#L136-L138) in `DefaultApplication`. (I am not sure about if I am wrong about that).

Is it possible to know the state of the application? For example, `Running`,  `Crashed` and so on?

Thanks a lot

**Comment by twoseat** [comment]
@kiuby88 You can use a `SummaryApplicationRequest` against the `CloudFoundryClient` to get the information you want, though according to [the API documentation](https://apidocs.cloudfoundry.org/239/apps/get_app_summary.html) you'll only see one of `STOPPED` or `STARTED`

You're right that we don't expose it at the operations level; we'll look at including that in a future release.

**Comment by kiuby88** [comment]
@twoseat thanks a lot. Currently, I am using `ApplicationDetail` to get this information and I use in my code a simple enum to wrap the status.

```    
public enum AppState {

        STARTED("STARTED"),
        STOPPED("STOPPED");

        private final String state;

        private AppState(final String state) {
            this.state = state;
        }

        @Override
        public String toString() {
            return state;
        }
    }
```

Thanks a lot for your response, in any case I will integrate your future updates in my code.

**Comment by nebhale** [comment]
If you take a look at the output of the CLI, the state of an application is represented as the "requested state" (which is started and stopped) and the state of an _instance_ is represented in the more fine grained states:

```plain
$: cf app java-main-application
Showing health and status for app java-main-application in org [REDACTED] / space [REDACTED] as bhale@pivotal.io...

name:              java-main-application
requested state:   started
instances:         1/1
usage:             1G x 1 instances
routes:            ben-java-main-application.cfapps.io
last uploaded:     Mon 23 Oct 15:23:39 PDT 2017
stack:             cflinuxfs2
buildpack:         https://github.com/cloudfoundry/java-buildpack.git

     state     since                  cpu    memory         disk           details
#0   running   2017-10-23T22:24:55Z   0.2%   323.6M of 1G   155.7M of 1G   
```

The client represents this information in the same way with [`ApplicationDetail.getRequestedState()`](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/3.1.0.RELEASE/org/cloudfoundry/operations/applications/ApplicationDetail.html#getRequestedState--) and [`InstanceDetail.getState()`](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/3.1.0.RELEASE/org/cloudfoundry/operations/applications/InstanceDetail.html#getState--).

In order to get an idea of whether all instances are running you might do something like the following:

```java
boolean isApplicationRunning(ApplicationDetail applicationDetail) {
    return applicationDetail.getInstanceDetails().stream()
        .map(InstanceDetail::getState)
        .allMatch("running"::equals);
}
```

In order to get the reduced collection of states (which you would then rank in order of severity) you might do something like the following:

```java
List<String> instanceStates(ApplicationDetail applicationDetail) {
    return applicationDetail.getInstanceDetails().stream()
        .map(InstanceDetail::getState)
        .distinct()
        .collect(Collectors.toList());
}
```
