### ISSUE TITLE
Knowing the bound services

### ISSUE THREAD

**Issue by kiuby88** [cloudfoundry/cf-java-client#553]
Hi, is it possible know the bound services to an application?

I have seen a method of `ServiceInstance` that provides the application that did `bind`. However, it would be reasonable to use a  method which provides all the bound services of an application. Is this something that will be added soon, or is there an alternative way of doing this from  `CloudFoundryOperations` level?
WDYT?

Thanks

**Comment by twoseat** [comment]
@kiuby88 We're using the CLI as a template, and I don't believe it provides this feature (if it does please let me know!) so we have no plan to introduce it in the near term.

It is possible at the `CloudFoundryClient` level (`client.applicationsv2.listServiceBindings()`), otherwise you may be able to extract what you want from `operations.applications.getApplicationManifest()`.

**Comment by kiuby88** [comment]
Thanks a lot @twoseat. I see your point, as you mentioned the CLI does not provides this feature.
