### ISSUE TITLE
how do we  use Operations Manager

### ISSUE THREAD

**Issue by shuchangbruce** [cloudfoundry/cf-java-client#592]
Hi there, a question regarding ops manager.
In command line I use
$  uaac target https://*****.org/uaa --skip-ssl-validation 
$ uaac token owner get 
$ uaac curl -k https://****.org/api/v0/diagnostic_report
.......
to check and operate ops manager. 

Now I'm thinking an automation tool to automatically check and update my products on ops manager.  I'm using java and I figure this library would be a good choice. Does this library offer such functions? If not, how could I reach my goal?

Thank you so much.

**Comment by nebhale** [comment]
Ops Manager isn't a Cloud Foundry open source project, instead it is a Pivotal commercial product.  Since this is the case, the Cloud Foundry Java Client isn't the appropriate place for that API.  You can make a request through Pivotal to have them create a library that exposes Java language bindings for those APIs.
