### ISSUE TITLE
AssociateSpaceManagerByUsernameRequest problem

### ISSUE THREAD

**Issue by geekyzk** [cloudfoundry/cf-java-client#673]
```
CreateOrganizationResponse orgInfo = cloudFoundryClient.organizations()
  .create(CreateOrganizationRequest.builder()
    .name(orgName)
    .build())
.block();

CreateSpaceResponse spaceInfo = cloudFoundryClient.spaces()
  .create(CreateSpaceRequest.builder()
    .organizationId(orgInfo.getMetadata().getId())
    .name("default")
    .build())
.block();

AssociateOrganizationManagerByUsernameResponse associateOrg = cloudFoundryClient.organizations()
  .associateManagerByUsername(AssociateOrganizationManagerByUsernameRequest.builder()
    .organizationId(orgInfo.getMetadata().getId())
    .username(userInfo.getUserName())
    .build())
.block();

cloudFoundryClient.spaces()
  .associateManagerByUsername(AssociateSpaceManagerByUsernameRequest.builder()
    .spaceId(spaceInfo.getMetadata().getId())
    .username(userInfo.getUserName())
    .build())
.block();
```

associate org is success.
associate space is error

```
org.cloudfoundry.client.v2.ClientV2Exception: CF-InvalidRelation(1002): Invalid relation: 1932e49c-a94a-45b7-8b56-961445465b86
```

i use cli is success,

```PS C:\Users\tian> cf set-space-role tian@1634122.com tstTIAN12322dfv default SpaceManager
Assigning role RoleSpaceManager to user tian@1634122.com in org tstTIAN12322dfv / space default as admin...
OK
```

I use these two ways to operate the admin

**Comment by nebhale** [comment]
@geekyzk We've got a [pretty solid test](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/java/org/cloudfoundry/client/v2/SpacesTest.java#L235) of assigning the space manager role via username that runs on CF instances up to a year old, so I'm confident in our implementation.  In addition, that you're getting an `InvalidRelation` error from the Cloud Controller implies that we've made a reasonable request, but the current model of org/space/user doesn't support the relationship that you're trying to build.  In other words, I believe that the request is being made correctly, but the inputs you're passing in are valid for the server you're calling.  If you set the `cloudfoundry-client` logger to `DEBUG` (using your normal logging configuration) you'll get a trace of the requests that were made and you should be able to see exactly where the error was, and what URIs were called to generate it.  That can be compared to the `CF_TRACE=true` output of the CLI to make sure the same endpoints are called in both cases.  Any discrepancies between the two are likely where the issue is.

**Comment by geekyzk** [comment]
@nebhale Thanks, successful solve this problem.
