### ISSUE TITLE
CF java client doppler issue

### ISSUE THREAD

**Issue by RaynDol** [cloudfoundry/cf-java-client#725]
use the java cf client, when I try to get the logs of the apps (via code) I got error: **DopplerClient must be set**

The error is coming from:

https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/_DefaultCloudFoundryOperations.java

line 163:

@twoseat @nebhale Any idea what I should do in order to use it ? any workaround ?
I was able to push the app ...

**Comment by nebhale** [comment]
The `DopplerClient` is the type that connects to the Doppler server in order to retrieve logs.  Much like the `CloudFoundryClient` is required in order to call the Cloud Foundry APIs, you must inject one of these if you wish to access logs.  The [Usage Documentation](https://github.com/cloudfoundry/cf-java-client#usage) describes exactly how this is done.
