### ISSUE TITLE
Gradle Plugin

### ISSUE THREAD

**Issue by elgohr** [cloudfoundry/cf-java-client#735]
Could you give me a hint where the Gradle plugin went to?
Since version 2.0 it disappeared from the repository. Is it no longer maintained?

**Comment by nebhale** [comment]
The Gradle was based on the 1.x branch of code which is no longer maintained, which results in the plugin not being maintained either.  At the moment, we have no plan to reintroduce it to the 2.x line, instead recommending a CI/CD pipeline that leverages the CF CLI directly.

If you have arguments as to why it should be re-introduced, I'm happy to listen to them.

**Comment by elgohr** [comment]
Actually there are developers out there, which have to arrange themselfs with let's _other_ build environments. Some still build in Jenkins, Bamboo or even worse.
In this way there are limitations, which make it hard to realize maintainable buildscripts using the CLI.

To make a concrete example: In Bamboo variable substitution only works in gradle.build. If you want to use secrets you can't simply write them into the manifest and do a cf push.
The workaround would be to do a cf push --no-start, cf set-env ..., cf start ...
So the script grows and is as understandable as a bash script can be.

Furthermore you're coupling your build to a shell-syntax.

**Comment by keeganwitt** [comment]
Couple inconveniences
1. If I have Jenkins multijobs that deploy a group of microservice apps, I need to either use Throttle Concurrent Builds Plugin to prevent deploys from happening at the same time, or have different Jenkins nodes for different foundation/org/space targets, or set a separate `CF_HOME` for each job so that apps don't get pushed to the wrong env since CLI targets wherever logged in and commands don't have a context that can be set.
1. If building a reusable set of scripts to do deploys using CLI, need to both restart and restage app so that env vars used by app or used by buildpack are both applied.  This means waiting for the app to completely start and give healthy response twice, which can be slow for bigger Spring apps for example.

**Comment by gmcouto** [comment]
The Jenkins plugin for CF is very bad for variable substitution. We ended up with a very hacky job...
I would prefer all that to be in the build.gradle with some parameters. Definetely would worth the re-open.

For now we will be testing as a replacement.
https://github.com/pivotalservices/ya-cf-app-gradle-plugin

**Comment by farrukhnajmi** [comment]
> For now we will be testing this as a replacement:
> https://github.com/pivotalservices/ya-cf-app-gradle-plugin

Above link is 404 now. What is the latest suggestion for a CF gradle plugin?
