### ISSUE TITLE
Create Getting Started Guide

### ISSUE THREAD

**Issue by twoseat** [cloudfoundry/cf-java-client#737]
Create an introduction to the client that goes beyond the readme.

**Comment by MFranca** [comment]
@twoseat @nebhale 
_Hey, Paul and Ben, not sure here is the best place to post this... :-)_
I'm doing some research and trying to get used to this library, but I'm having a hard time since apparently there is no much documentation (samples). And, again, I couldn't even find a discussion list or something like that, so I could submit my questions...
**Is there any "draft" version of this Getting Started Guide? (may I help with this?)
In the meantime, could you provide any guidance at all? I just want to do 2 things:**
1) validate credentials, i.e., try to connect/login and be able to catch an exception (**UaaException**). Apparently this exception (unauthorized/authentication failure) is not "catchable" by a standard try-catch block... :-(
2) get a list of all available services... I'm trying the code below, but apparently I need to instantiate a "**ListServiceOfferingsRequest**" object, but I really don't know how to... :-(
Is there any email, or discussion list/wiki I can interact with other developers using this library?
Thanks in advance!

**Comment by nebhale** [comment]
@MFranca There is no draft version of this guide.  However, a couple of pointers for you.

1.  The client is based on a Project Reactor, a reactive framework for Java.  As you've identified, reactive frameworks like this do not throw exceptions in the same way that idiomatic Java does.  Your best bet is to take a look at either [Reactor's documentation](https://projectreactor.io/learn) or our [examples](https://github.com/cloudfoundry/cf-java-client#cloudfoundryclient-apis).
1.  The best set of examples for using the library is the extensive list of [integration tests](https://github.com/cloudfoundry/cf-java-client/tree/master/integration-test/src/test/java/org/cloudfoundry).  Specifically, listing all available services can be found [here](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/java/org/cloudfoundry/client/v2/ServicesTest.java#L193-L224).

Beyond the samples, the #java-client channel on https://cloudfoundry.slack.com is where real-time support can be found.
