### ISSUE TITLE
How to handle credentials change in client code (question

### ISSUE THREAD

**Issue by i300543** [cloudfoundry/cf-java-client#750]
Hello, 
i am trying to handle correctly credentials change in runtime: i.e. the client has been initialized, and is stored in memory. After a short period, the user has changed his cf credentials, which are used to initialize the client using PasswordGrantTokenProvider.

I am trying to handle the failure that will occur the next time cf operation is attempted. I assume UnknownCloudFoundryException will be thrown as a result , correct ? if not, then which one ?
also i am redirecting all the mono operations ending with block() to this code:
```
 private Object executeMono(Mono<?> mono) {
        try {
            return mono.block(Duration.ofSeconds(45));
        } catch (UnknownCloudFoundryException e) {
            // TODO check if this is the only use case
            if (e.getStatusCode() == Status.UNAUTHORIZED.getStatusCode()) {
                sm.flushUserData(endpoint);
                LOG.debug("flushed user data for endpoint: ", endpoint.toExternalForm());
            }
            LOG.debug("Exception while executing CloudFoundryOperation: ", e);
            throw e;
        } catch (Exception e) {
            LOG.error("Error while executing CloudFoundryOperation: ", e);
            throw e;
        }

    }
```

flushUserData basically resets the inmemory struct containing the cf client, which will cause reinitialization on next request.

Am i missing something ? is there a better way to handle this scenario ?

Thanks in advance,
Sergey

**Comment by nebhale** [comment]
The [token negotiation flow](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/tokenprovider/AbstractUaaTokenProvider.java#L248) follows a three step process.

1.  Attempt to use existing token
1.  If existing token usage returns a 401, attempt to negotiate a new token with a refresh token (assuming one exists)
1.  If refresh token negotiation returns a 401, attempt to negotiate a new token with the "primary" token strategy (username/password in your case)
1.  If primary token negotiation returns a 401, fail back to user

Since the failure that would propagate out of a change to user credentials is against the UAA (where tokens are negotiated), the exception you'd receive is actually a [`UaaException`](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/uaa/UaaException.java#L24).  That exception will contain any error details returned by the UAA about what has caused the failure.  I believe that `error` might come back with something like `bad_credentials` (which you'd filter on), but you should reproduce the issue directly to ensure that my guess there is correct.

**Comment by i300543** [comment]
thank you for the quick answer!

Best regards,
Sergey
