### ISSUE TITLE
best practices for access and refresh token re-use

### ISSUE THREAD

**Issue by cwesdorp** [cloudfoundry/cf-java-client#775]
What is considered the best usage of creating a CF client when we have an access and refresh token stored (like the CLI client does)?

Current we use the `PasswordGrantTokenProvider` to extract the access and refresh token from the login response and store that locally. When we need to connect to CF again (with a new instance of the client) we implemented a class from the `TokenProvider` interface that has the accessToken, and when this is invalid we renew it in the invalidate() method using a `RefreshTokenGrantProvider`. 

So the question is, what is the best approach to create a `TokenProvider` with a known access and refresh token? 

Our current implementation looks like this 

```
final Properties props = new Properties();
TokenProvider tp = new TokenProvider() {
    
    Mono<String> accessToken = Mono.just(props.getProperty("accessToken"));
    
    @Override
    public Mono<String> getToken(ConnectionContext connectionContext) {
        return accessToken;
    }

    @Override
    public void invalidate(ConnectionContext connectionContext) {
        DefaultConnectionContext newConCtx = DefaultConnectionContext.builder().from(connectionContext).build();
        RefreshTokenGrantTokenProvider newToken = RefreshTokenGrantTokenProvider.builder()
            .token(props.getProperty("refreshToken"))
            .build();
        
        try {
            accessToken = newToken.getToken(newConCtx)
                    .doOnSuccess(s -> System.out.println("Got a new token: " + s));
        } catch (Exception e) {
            throw new IllegalStateException("Something is wrong renewing our token", e);
            
        }
        System.out.println("We'll get you a new token!");
    }
};
````

Please advice

**Comment by nebhale** [comment]
The short answer is no, the access token should never be stored anywhere.  The access token is very short lived (5 minutes in many/most cases) and can always be renegotiated using a longer-lived set of credentials or refresh token.  So in general, you should only store the refresh token and use the `RefreshTokenGrantTokenProvider` with that.  If token negotiation with that fails (because the refresh token has expired, typically after a week) then fall back to prompting the user for a set of credentials using the `PasswordGrantTokenProvider` or something similar.

The Spring Tool Suite actually does this very thing, and @kdvolder might have some more insight.

**Comment by kdvolder** [comment]
Ben summarized it nicely, I think. All I can do is add some comments about precisely what STS does.

We give the user two different options to do a *first time*  'login'.

1. Via a username + password 
2. Via a one-time access token that you can get from the CF web ui. (Some Pivotal clients insisted on this for security reasons, as it provides a very strong guarantee the password is never stored).

We also provide 3 options for 'storing' the credentials (so that STS can auto-login on a next session).

1. Store username & password
2. Store the oauth *refresh* token
3. Do not store anything (requires the user to provide credentials each time they start STS)

If you do not want to give the user a lot of options to choose from (makes things a bit complex to implement correctly). I think a good compromise would be to have them login with username + password. Then grab the refresh token and store it for the next session.

**Comment by kdvolder** [comment]
> The short answer is no, the access token should never be stored anywhere

I think that's right, though the word 'should' may be a bit too strong. I don't think its 'dangerous' to store the access token, but it just doesn't make much sense because its short lifespan makes it rather pointless a thing to store and hang onto. The CLI does indeed store it. Most likely because its internal representation of OAuth token contains both the refresh and access tokens and its just easier for them to store and load them both.

For the cf-java-client you only really have easy access via public apis to the refresh token. And the api is designed so you can store just that and then later use it with a  `RefreshTokenGrantTokenProvider`. So with the cf-java-client you should only store the refresh token.

Oh yeah. One other potentially useful tidbit. It is also possible to read the `config.json` file cf cli saves on disk, extract the refresh token from that, and use if with cf-java-client's `RefreshTokenGrantTokenProvider`. This is something we do for our manifest.yml editor extension to VSCode, so that it can provide 'smart' content assist based on what target you are currently logged into via the cf cli.

**Comment by nebhale** [comment]
> The CLI does indeed store it. Most likely because its internal representation of OAuth token contains both the refresh and access tokens and its just easier for them to store and load them both.

I think this is also related to the fact that the process using the access token lives and dies many times within the lifespan of an access token.  Effectively they _can't_ cache the access token in memory for many uses during its life because the process terminates; instead they cache the access token to disk.  The Java Client is quite different in this regard because the process will typically outlive the access token.  If you're writing some kind of application that has the same lifecycle as the CLI, then it might be interesting to persist the access token as well, but again, not required.

**Comment by cwesdorp** [comment]
> Effectively they can't cache the access token in memory for many uses during its life because the process terminates
This is sort of the same for use because we use the CF client from a web application, different users, different targets. There is a small performance penalty to this because getting a new access token requires two additional calls to the CF end point (info and refresh). We need to check how to optimize this. 

Thanks for clarifying this. But this i'll consider the item resolved.

**Comment by nebhale** [comment]
@cwesdorp It's important to remember that there are only two types that maintain any significant state, the `ConnectionContext` and the `TokenProvider`.  In your multi-tenant situation I'd recommend having

- A single `ConnectionContext` used by all requests (if there is a single target host, multiple if there are multiple target hosts)
- Multiple *cached* (LRU?) `TokenProvider`s keyed by the user
- Disposable `*Client`s created on each incoming request

By far the most expensive (resource-wise) component is the `ConnectionContext`.  It contains the thread and connection pools and is designed to be used for any and all requests, even with different users.  The `TokenProviders` store valid tokens, resulting in fewer network calls for them and renegotiate when a `401` is received.  Since there is some unnecessary overhead in negotiating a token when you've got a valid one it makes sense to cache these.  Beyond that, a `CloudFoundryClient` (and its peers) is totally stateless, simply combining a `ConnectionContext` and a `TokenProvider` to make a REST call.  You can create and destroy these quickly, easily, and regularly with no real penalty.

The client is designed so that you can mux `ConnectionContext`s and `TokenProviders` in any combination and they'll behave properly.  This allows you to cache expensive resources in memory and mix and match them in lightweight clients as needed.

**Comment by cwesdorp** [comment]
@nebhale Thanks for the guide lines. I'll understand the idea and have a sample application from which I came to that conclusion, good that you confirm this.
