### ISSUE TITLE
Add `dispose` method to `ConnectionContext` ?

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry/cf-java-client#777]
Recently a `dispose` method was added to `DefaultConnectionContext` (thanks again for that by the way).

Shouldn't it also be added to the `ConnectionContext` interface?

Not sure about this, so feel free to disregard this suggestion if it seems misguided.

The reason, I make this suggestion... I just got a little confused because I *knew* you added "some method to clean stuff up", but I couldn't find it in the any of the interfaces which I sort of considered to be 'the public api'. I had to go digout the issue and its corresponding commit from the project history to see where you actually added it.

So, I think, the dispose method might be slightly easier to find if it was added to ConnectionContext.

**Comment by nebhale** [comment]
I went back and forth on this and in the end decided that `dispose()` wasn't part of the core contract for a `ConnectionContext`.  I could imagine (and in fact have implemented in test code) a `ConnectionContext` that doesn't need to dispose of any resources.  In order to mitigate the fact that this method would be a bit hidden if it wasn't on the public interface, I even [added `@PreDestroy`](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/_DefaultConnectionContext.java#L74) to the method so it would be called automatically for Spring/CDI systems.  I know this doesn't help you specifically, but it is something that I struggled with a bit.

**Comment by kdvolder** [comment]
If some implementation of ConnectionContext don't need any explicit cleanup, then it could just provide a empty implementation.

Anyhoo, I don't feel strongly about it. I see it wasn't a simple oversight but a deliberate choice. So feel free to close this ticket if you want to stick to your earlier choice of hiding that method somewhat.

**Comment by nebhale** [comment]
I'll close this out as an explicit choice.  Thanks for keeping us honest.
