### ISSUE TITLE
Status and future plans for cloudfoundry-client-lib

### ISSUE THREAD

**Issue by jamsden** [cloudfoundry/cf-java-client#805]
I'm having trouble understanding the relationship between cloudfoundry-client-lib and cf-java-client. 

1. Is cloudfoundry-client-lib still maintained?

2. Is it a subset of cf-java-client somehow?

3. Its performance is pretty limited, are there other realizations that might fit better with different platform architectures (e.g., not Spring) and perhaps perform better?

4. There are some old dependencies in the pom.xml file that cause Jetty applications to fail to start properly. Getting incompatible version of servlet-api that is missing methods.

**Comment by nebhale** [comment]
1.  The CF Java Client library is under active development, but the artifact names have changed with the change to the programming model that came with 2.0.  The `cloudfoundry-client-lib` artifact has been end-of-life since the [`1.1.4.RELEASE` on January 4, 2016](https://github.com/cloudfoundry/cf-java-client/releases/tag/v1.1.4.RELEASE).

2.  It is not a subset, but rather a much larger superset.  If you look at the [API documentation](https://github.com/cloudfoundry/cf-java-client#cloud-foundry-java-client), you'll notice that we cover not only a much larger percentage of the REST APIs (~550 of the ~700 with a commitment to finish them all), but we also have an Operations API that emulates the CF CLI interface.

3.  I'm not sure what you mean by performance being limited.  In general, the performance of doing anything against the Cloud Controller is governed by the Cloud Controller performance and network link.  Using Spring as a library for making REST calls wouldn't impact the performance of these calls in any meaningful way when compared to the performance of the Cloud Controller and network.

4.  The project has had 33 releases since the version you're likely using, and I think you'll find that the dependences are up to date in those releases.

**Comment by jamsden** [comment]
So the (synchronous) programming style in cloudfoundry-client-lib is no longer supported? Or is there a compatibility layer I'm missing?

I couldn't get the example in the API documentation to login to Bluemix - I don't get any errors, but don't get any results either. I can get cloudfoundry-client-lib to login.

**Comment by nebhale** [comment]
Correct, the `cloudfoundry-client-lib` implementation is no longer supported.  We found, when speaking to users, that the blocking model did not scale to the requirements that users were placing on it.  Keeping large blocking connection and thread pools would artificially limit the number of requests that a given application could handle.  The request to use a non-blocking API was deemed to be the best way to match up with the fact that the client could handle many requests, but spent the majority of it's time in a blocking state, waiting for the Cloud Controller to return.

Using the [example from the documentation](https://github.com/cloudfoundry/cf-java-client#cloudfoundryclient-apis) against BlueMix seems to work:

```java
public final class Test {

    public static void main(String[] args) throws InterruptedException {
        DefaultConnectionContext connectionContext = DefaultConnectionContext.builder()
            .apiHost("api.ng.bluemix.net")
            .build();

        PasswordGrantTokenProvider tokenProvider = PasswordGrantTokenProvider.builder()
            .password("[REDACTED]")
            .username("[REDACTED]")
            .build();

        ReactorCloudFoundryClient cloudFoundryClient = ReactorCloudFoundryClient.builder()
            .connectionContext(connectionContext)
            .tokenProvider(tokenProvider)
            .build();

        CountDownLatch latch = new CountDownLatch(1);

        cloudFoundryClient.organizations()
            .list(ListOrganizationsRequest.builder()
                .page(1)
                .build())
            .flatMapIterable(ListOrganizationsResponse::getResources)
            .map(resource -> OrganizationSummary.builder()
                .id(resource.getMetadata().getId())
                .name(resource.getEntity().getName())
                .build())
            .subscribe(System.out::println, t -> {
                t.printStackTrace();
                latch.countDown();
            }, latch::countDown);

        latch.await();
    }

}
```

```plain
cloudfoundry-client.request           GET    https://api.ng.bluemix.net:443/v2/organizations?page=1
cloudfoundry-client.request           GET    https://api.ng.bluemix.net:443/v2/info
cloudfoundry-client.response          200    https://api.ng.bluemix.net:443/v2/info (212 ms)
cloudfoundry-client.request           POST   https://login.ng.bluemix.net:443/UAALoginServerWAR/oauth/token
cloudfoundry-client.response          200    https://login.ng.bluemix.net:443/UAALoginServerWAR/oauth/token (3.3 s)
cloudfoundry-client.response          200    https://api.ng.bluemix.net:443/v2/organizations?page=1 (5.0 s)
OrganizationSummary{id=66225cf5-f176-4f34-b122-a2dea6b277b5, name=bhale}
```

If you're not familiar with reactive/non-blocking/multi-threaded programming, I encourage you to review the [Project Reactor Reference Documentation](https://projectreactor.io/docs/core/release/reference/) as a good intro.

**Comment by jamsden** [comment]
I got it. I needed the CountDownLatch to prevent the program from terminating before the results were printed.

**Comment by nebhale** [comment]
Great!  Good luck.
