### ISSUE TITLE
How to create an event for an application using java client lib ? For example.  i want to create an event, when app usage goes more than 80 percent, another api should be called. Not able to find in 1.1.3

### ISSUE THREAD

**Issue by georgian3590** [cloudfoundry/cf-java-client#824]

**Comment by nebhale** [comment]
To start with the 1.x line of the Java Client is no longer supported and you should use the 2.x or 3.x line in order to stay on supported code.  Examples of using the 2.x and 3.x lines can be found in the [README of the project](https://github.com/cloudfoundry/cf-java-client#cloudfoundryoperations-apis).  I’d recommend taking a look at [`Applications.get()`](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/3.0.0.RELEASE/org/cloudfoundry/operations/applications/Applications.html#get-org.cloudfoundry.operations.applications.GetApplicationRequest-) to start as this API should return statistics about the application’s instances and resource consumption.
