### ISSUE TITLE
How to write Flux<byte[]> to a file 

### ISSUE THREAD

**Issue by gowriln** [cloudfoundry/cf-java-client#844]
The API to download CF app bits  returns an object of `Flux<byte[]>` .	
```
passwordGrantTokenProvider = PasswordGrantTokenProvider.builder()
    .password(password)
    .username(emailId)
    .build();

cfops = DefaultCloudFoundryOperations.builder()
    .cloudFoundryClient(getReactorCloudFoundryClient(connectionContext,passwordGrantTokenProvider))
    .organization(orgName)
    .space(spaceName)
    .build();

Flux<byte[]> fluxbyte = cfops.getCloudFoundryClient()
    .applicationsV2()
    .download(request); 
```

**How to write  the received app bits content into a file ?**

**Comment by nebhale** [comment]
Unfortunately, there's no great answer today for reactively writing to a file.  An example (that's too verbose) would be:

```java
Path location = Paths.get("test-output.zip");

this.cloudFoundryClient.applicationsV2()
    .download(DownloadApplicationRequest.builder()
        .applicationId("test-application-id")
        .build())
    .publishOn(Schedulers.elastic())
    .reduceWith(() -> {
        try {
            return Files.newOutputStream(location);
        } catch (IOException e) {
            throw Exceptions.propagate(e);
        }
    }, (out, bytes) -> {
        try {
            out.write(bytes);
            return out;
        } catch (IOException e) {
            throw Exceptions.propagate(e);
        }
    })
    .doOnSuccessOrError((out, t) -> {
        try {
            out.close();
        } catch (IOException e) {
            throw Exceptions.propagate(e);
        }
    })
    .map(out -> location);
```

I know that the Reactor team is working on a more "reactive native" style of this same thing.

**Comment by gowriln** [comment]
Hi , Thanks for the information. I tried the above but I am not able to get the app bit s.  It does not give any error but it does not enter  the following part of code `.publishOn(Schedulers.elastic()).reduceWith(() -> {
        try {
            return Files.newOutputStream(location);
        } catch (IOException e) {
            throw Exceptions.propagate(e);
        }`
**I am trying to implement  CF API [Download App bits API](https://apidocs.cloudfoundry.org/280/apps/downloads_the_bits_for_an_app.html)  using Java client. I am able to execute the command using CLI but not using java client.  Could you please help me with this ?**

**Comment by nebhale** [comment]
It’s almost certainly because you haven’t subscribed and caused the execution to start.  Please take a moment to review [how Reactor works](http://projectreactor.io/learn) and how you might [deal with non-blocking asynchronous code](https://springoneplatform.io/sessions/designing-implementing-and-using-reactive-apis) (specifically `CountDownLatch` and `.block()`).

**Comment by tsgautier** [comment]
Correct me if I am wrong - but using an OutputStream inside a Flux is not correct.  You're using blocking IO inside a non-blocking context.  

I don't quite know what the code would be - but it seems to me the right way would be to get a Channel e.g. Files.newByteChannel(...)

**Comment by nebhale** [comment]
This is why we push it onto a different thread.  Interacting with blocking (or even long-running) APIs is a fact of life, in the reactive world and the key here is that we want to get the blocking/long-running operation off of the critical thread (Netty reception in this case) to do it's work and allow subsequent responses to be processed.  The `ByteChannel` is going to have a similar problem (even if it's not blocking, it can hijack the reception thread while the very slow spinning disk writes data) which is why there isn't a good answer today, and is something that the Reactor team is looking at.

**Comment by tsgautier** [comment]
True - there is no true async file IO in Java so therefore at some point you're going to hit a thread pool.
