### ISSUE TITLE
CF-StatsUnavailable(200002): Stats unavailable: Stats server temporarily unavailable

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#846]
Hi,
We are getting this error for cloud foundry application detail API:

```
Flux<ApplicationSummary> applicationSummaryFlux = defaultCloudFoundryOperations.applications()
    .list();

if (CollectionUtils.isNotEmpty(applicationSummaryFlux.collectList().block())) {
    applicationSummaryFlux.toIterable().iterator()
        .forEachRemaining(applicationSummary -> {
            ApplicationDetail applicationDetail = defaultCloudFoundryOperations.applications()                              
                .get(GetApplicationRequest.builder()
                    .name(applicationSummary.getName())
                    .build())
                .block();
        });
}
```

**Comment by twoseat** [comment]
Hi @parasuramln. Having done some investigating there appear to be 2 parts to this problem. The first is that the error message you're getting generally means that there is something wrong with your cloud foundry configuration (though it could just be a transient networking glitch, for example). So you should take steps to try to identify and fix what's wrong.

The second part is how we should handle the error if it does appear. Some errors are expected (e.g. an app that is stopped gives an error because it has no stats to report, and we handle that), but because this one _probably_ indicates a genuine error it might be best for us to pass it on as we now do. I'll speak to a colleague and we'll come up with a plan.

**Comment by twoseat** [comment]
Having looked into this some more my initial suspicion was right - if you see this error it means your system is misconfigured, and the only sensible thing we can do is pass the error on.
