### ISSUE TITLE
Restarting 500+ micro services effectively.

### ISSUE THREAD

**Issue by r2d2c3p0** [cloudfoundry/cf-java-client#870]
Hello,

Imagine a situation where you have 500+ micro services (multiple Spaces and Orgs) in one foundation and you need to restart them quick and effectively, how can I achieve with this client?

r2d2c3p0

**Comment by nebhale** [comment]
I’d use [`Applications#restart()`](https://static.javadoc.io/org.cloudfoundry/cloudfoundry-operations/3.8.0.RELEASE/org/cloudfoundry/operations/applications/Applications.html#restart-org.cloudfoundry.operations.applications.RestartApplicationRequest-).  Due to the non-blocking nature of the client, the requests will be parallelized.  The biggest concern at that point is whether the Cloud Controller can handle the load of doing all of them in near-perfect parallel.

**Comment by r2d2c3p0** [comment]
Thanks Ben !!! I will share this with my support teams.

**Comment by r2d2c3p0** [comment]
Thanks Ben, I am closing this QA (issue).
