### ISSUE TITLE
How to pull the recent log of a cf application using cf java client ?

### ISSUE THREAD

**Issue by dasguptaeesudipto** [cloudfoundry/cf-java-client#900]
How to pull the recent log of a cf application using cf java client ?

Can i have the proper implementation  details to pull the recent logs for a application using cf java client ?

I need an example code if any  to check . Please help .

**Comment by twoseat** [comment]
The specific call you need looks like this:

```
this.cloudFoundryOperations.applications()
            .logs(LogsRequest.builder()
                .name("your-app-name")
                .recent(true)
                .build())
```
But on its own this won't do anything - you need all the infrastructure to connect to your Cloud Foundry instance (as detailed in the [README](https://github.com/cloudfoundry/cf-java-client#cloudfoundryoperations-builder)), and you need to be able to subscribe to and consume the result of the call. As has been pointed out, you won't be able to do that without first understanding something about reactive programming.

In addition we can't simple provide the code because it's both too complicated and too dependent on the specifics of your situation (take a look at the configuration of our [integration tests](https://github.com/cloudfoundry/cf-java-client/blob/master/integration-test/src/test/java/org/cloudfoundry/IntegrationTestConfiguration.java) to understand what you might need to do, and why we can't just write something for you).

**Comment by dasguptaeesudipto** [comment]
can you please provide some more details  to build up the code to  capture the logs ? What are the extra  set up needed ?
