### ISSUE TITLE
How to achieve concurrency ?

### ISSUE THREAD

**Issue by paroshdey** [cloudfoundry/cf-java-client#902]
How do i achieve concurrency using the java clients, suppose i want to invoke multiple APIs one after the other but after 2 api calls the 3rd api fails so the previous 2 susscesfull api should also rollback . are there any out of box solutions provided?

**Comment by nebhale** [comment]
There is nothing provided out of the box around automated rollback.  Users would be responsible for using reactive operators like [`onErrorResume()`](
https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#onErrorResume-java.lang.Class-java.util.function.Function-) in order to write error compensation code.

The Java Client is intended to be a low-level building block for using the Cloud Foundry REST API and doesn't consider behavior like this within scope.  That being said, an additional library built on top (or a library of utilities to be used _with_ the client) makes a lot of sense.
