### ISSUE TITLE
Buildpacks support is not available.(The singular buildpack field in manifests is deprecated)

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#921]
as per CLI
https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#buildpack-deprecated

buildpack is deprecated and it is replaced with buildpacks ,but [**ApplicationManifest**](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/_ApplicationManifest.java) doesn't support it as of now

**Comment by parasuramln** [comment]
Hi,

When CF java client gonna support. Buildpacks ??

**Comment by twoseat** [comment]
Hi @parasuramln I'm almost done with the code, so I expect it will be in a build snapshot in the next few days.

**Comment by adwaitabhandare** [comment]
Any update on this.

**Comment by twoseat** [comment]
@parasuramln With apologies for the continuing delay, this has turned out to be somewhat more complicated than I'd expected - although the singular buildpack is deprecated from manifests, the v2 api that we need to continue support for still assumes a single buildpack. I'm working on a fix that allows for both, but it will have to wait for the imminent netty upgrade release to be out of the way.

**Comment by BernhardDenner** [comment]
Any news on this issue? We miss this in 4.3.0.RELEASE

**Comment by twoseat** [comment]
I'm afraid this issue has slipped down the priority list, and I can't currently commit to a particular release.
