### ISSUE TITLE
How to set invocation timeout for health check of a CF application using cf-java-client?

### ISSUE THREAD

**Issue by sg1702** [cloudfoundry/cf-java-client#933]
Is there any API which I can use to set the invocation timeout for health check?

**Comment by twoseat** [comment]
Is [this](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/applications/_CreateApplicationRequest.java#L128) what you mean?

**Comment by narenchoudhary** [comment]
@twoseat Is there any update on this feature?

**Comment by boyan-velinov** [comment]
@twoseat As far as I can see it is not yet implemented. Is that correct?
I was checking in 4.xx in v3 _CreateApplicationRequest. So far we are using _CreateApplicationRequest v2 where we pass healtcheck endpoint and timeout

**Comment by twoseat** [comment]
The underlying call that the cli command makes is to update a process (https://github.com/cloudfoundry/cf-java-client/blob/main/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/processes/_UpdateProcessRequest.java), and the specific parameter set is in https://github.com/cloudfoundry/cf-java-client/blob/main/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v3/processes/_Data.java#L40

If you're happy with this please close this issue, otherwise let me know!

**Comment by boyan-velinov** [comment]
Thanks for clarifying 👍

**Comment by 360608** [comment]
in the manifest.yml file you can specify it

---
applications:
- name: my-microservice
  health-check-type: http
  health-check-http-endpoint: /actuator/health
  timeout: 180
  health-check-invocation-timeout: 10
