### ISSUE TITLE
VerifyUser of the foundation

### ISSUE THREAD

**Issue by kannan0501** [cloudfoundry/cf-java-client#979]
tried verify the user of the foundation by below snippet
VerifyUserResponse verifyUserResponse = users
                .verify(verifyUserRequest)
                .block();
it always throws exceptions for all userids
as org.cloudfoundry.uaa.UaaException: scim_resource_not_found: User sampleUser does not exist
it is the right way to verify the user of the foundation ?

**Comment by dmikusa-pivotal** [comment]
This is really a question about how to use the API. The client here is just allowing you to submit the request. What you put in the request is what's causing the problem here.  See https://docs.cloudfoundry.org/api/uaa/version/75.14.0/index.html#verify-user for details on how to use that request.

Closing this as there have been no recent updates.
