### ISSUE TITLE
how to get X-Vcap-Request-Id (unique id generated for each cloud_controller interaction)

### ISSUE THREAD

**Issue by parasuramln** [cloudfoundry/cf-java-client#981]
how to get X-Vcap-Request-Id (unique id for generated for each cloud_controller interaction) ?
![image](https://user-images.githubusercontent.com/22343548/62369827-8847e380-b54e-11e9-91f5-9ea8e7c44eb9.png)

**Comment by sms0070** [comment]
Is this possible or needs to be contributed?

**Comment by twoseat** [comment]
Can you explain the business case for it? At the operations level we could generate dozens of interactions for a single transaction, and I can't immediately picture what reporting each of those would look like.

**Comment by sms0070** [comment]
Hi @twoseat,

We have the following setup in our organisation. 

> one team(CF team) is responsible for developing of cf related stuff. Creation of services, launching of applications.

> other team(mine) works on applications that communicate with CF team's product. We use cf-Java-client. 

Now, for quite some time we've been experiencing issues with CF team regarding slow service creation, APIs returning 5xx responses. 

However,  since the number of calls is very high, they need either X-Vcap-Request-id or the timestamp at which the exact CF api call was made to track down the request.

This has become a bottleneck in all our communications with the CF team. That's why wanted to check here if it's possible to get the same.
