### ISSUE TITLE
CloudFoundryClient takes minutes to connect

### ISSUE THREAD

**Issue by jamesmasterskr** [cloudfoundry/cf-java-client#998]
This call now takes approximately 140 seconds:

`CloudFoundryClient cloudFoundryClient = new CloudFoundryClient(cloudCredentials,cfApi,"org","space");`

CF API version: 2.131.0
Client API v: 1.1.4.RELEASE

**Comment by nictas** [comment]
Hi @jamesmasterskr,

That's probably because the constructor tries to list all spaces that are visible to your user and then looks for the one that matches the `org` and `space` strings you've given as arguments (see [here](https://github.com/cloudfoundry/cf-java-client/blob/3978329ec83ff67661f69fadcef089bcd86e7b12/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/rest/CloudControllerClientImpl.java#L172) and [here](https://github.com/cloudfoundry/cf-java-client/blob/3978329ec83ff67661f69fadcef089bcd86e7b12/cloudfoundry-client-lib/src/main/java/org/cloudfoundry/client/lib/rest/CloudControllerClientImpl.java#L2526)). I suggest switching to a newer version of the cf-java-client, because 1.1.4.RELEASE is not supported AFAIK and I would not expect a fix for this codeline.

**Comment by jamesmasterskr** [comment]
Thanks @nictas. Trying to get a list of spaces with the new 3.15 client

`cloudFoundryOperations.spaces().list().map(SpaceSummary::getName)
                .subscribe(System.out::println);`

Nothing getting printed out. I'm clearly missing something obvious. Any help appreciated.

**Comment by nictas** [comment]
If there are no other statements after this one, then the program would just terminate without waiting for the operation to complete. That's because everything in the 3.x client is asynchronous by default. If you want to wait for the operation to complete, you need to call one of the `.blockX()` methods:
```
operations.spaces().list().map(SpaceSummary::getName).doOnNext(System.out::println).blockLast();
```
You can read more about reactive streams [here](https://projectreactor.io/).

**Comment by twoseat** [comment]
Everything @nictas has said is correct, but to emphasise a couple of points:
1. The CF endpoints that the `1.x` line relies on are being deprecated at the moment, so not only is it unsupported, it also _will_ stop working before too long.
2. While it's true that `.blockX()` is one way to get the results you need, in general this is not how you'll want to write your code. As an example, all of the code here is reactive, and excluding tests we use `.block()` once! So it's well worth your time to learn the basics of reactive programming. There's a good introduction [here](https://projectreactor.io/docs/core/release/reference/#intro-reactive).

I'm going to close this issue as answered now, but if you find any more problems please do open a new issue.
